Add top header and images for mobile home page
herokudev/Figma-design pull request #1
Opened 2021-07-08 15:29 UTC by herokudev

In this feature we have:

1. The main toolbar of header.
2. Headline section.
3. Social icons section.

2021-07-08 16:10 UTC, ZawadiSumba66 requested changes
### Hi @herokudev , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 

You have submitted a project which has one linter check failing. All the checks should pass in order for the review to commence

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-07-08 22:54 UTC, emmanuellekamwa requested changes
**STATUS: CHANGES REQUESTED 🛑🛑**
Hello @herokudev 👋🏽
Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Check the comments under the review._ 👀👇🏽
- I just want to add that you really have to stick to the design as much as possible but I know you can do this 💪🏽.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] I will only suggest you should add a live demo link to your readme file to make it look more professional.

Cheers and Happy coding!👏🏽👏🏽👨🏽‍💻👨🏽‍💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 22:54 UTC, emmanuellekamwa commented on css/style.css
> +}
- [ ] You have to use flexbox to align the content of the container. Please try to apply this method to your code.
- [ ] The section uses the font and colors (background and font) defined for the template

2021-07-08 22:54 UTC, emmanuellekamwa commented on index.html
> +        </div>
- [ ] The container of the section is a `section` tag. Please apply this change to your code.
- [ ] The section has the proper background image (decorations are always background images, not `img` tags)
- [ ] The section uses the font and colors (background and font) defined for the template
- [ ] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag). For the icons, it is preferable to use icons than images. Please kindly fix that.

2021-07-09 22:47 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️ 

## Hello @herokudev ✋🏼  Nice done with working on last review.However there are still some issues you should fix. Please fix them then your project will be approved.



### ♻️ Request changes ♻️
 

_**Check the comment about that  under the review.**_



### OPTIONAL SUGGESTIONS

#### These are optional 

- [ ]  Instead of using pictures for icons you can use icons from [font-awesome](https://fontawesome.com/start). 
### Cheers and Happy coding! 💻 👏
![cat on laptop](https://media.giphy.com/media/TilmLMmWrRYYHjLfub/giphy.gif)

___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

2021-07-09 22:47 UTC, ahmetbozaci commented on index.html
> +        <aside></aside>
**OPTIONAL**

- [ ] `Aside `tag is empty you can delete it.

2021-07-09 22:47 UTC, ahmetbozaci commented on index.html
> +                    <h1 class="main-title">I'm Herbert</h1>
**OPTIONAL**
- [ ] You can use only one `h1 `tag and combine these. Also for good practise you have to use only one `h1 `tag
- [ ] No need to wrapped by hgroup

2021-07-09 22:47 UTC, ahmetbozaci commented on index.html
> +                    </em>
**OPTIONAL**

- [ ] no need wrapped by `em `tag. you can delete it.

2021-07-09 22:47 UTC, ahmetbozaci commented on index.html
> +        </footer>
- [ ] This is not footer ,like last TSE review you should use `section `tag. You can use only `ul` tag. You wrap this icon by `a `tag in every `li `tag. It will be` ul>li>a`
____
**OPTIONAL**
- [ ] Instead of using pictures for icons you can use icons from [font-awesome](https://fontawesome.com/start).

2021-07-09 22:47 UTC, ahmetbozaci commented on css/style.css
> +
**OPTIONAL**
- [ ] For DRY css you should combine duplicate properties. 
You can create class `.d-flex { display: flex}` and use this class in html file.

- For more information about DRY principles you can check this [article](https://www.freecodecamp.org/news/7-important-tips-for-writing-better-css/)

2021-07-13 16:46 UTC, Shaher-11 requested changes
#### Hello @herokudev

### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:smiley::smiley:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] You must stick to the design as much as possible (e.g. font, colors, images, tests, margins)  using the templates in [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471).
- [ ] Check the comments below:point_down:


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

2021-07-13 16:46 UTC, Shaher-11 commented on index.html
> +                    </h1>
You need to center the element and reduce the font size as shown in the original design below
#### Original Design
![right1](https://user-images.githubusercontent.com/58376020/125491321-0996cb53-b45f-4c96-88db-560dfadd866a.png)

#### Your Project
![wrong1](https://user-images.githubusercontent.com/58376020/125491347-e19434fc-5e04-4b6c-89a3-3f48b60b9f35.png)

2021-07-13 16:46 UTC, Shaher-11 commented on index.html
> +            </nav>
Change the background color here to match the one in the given design 
![right2](https://user-images.githubusercontent.com/58376020/125491521-77e447b4-441c-4cc0-8250-376e0ac9185e.png)

2021-07-13 16:46 UTC, Shaher-11 commented on index.html
> +                    </em>
Delete the em tag and increase the font size as well as centering the text as the difference shown below
#### Original design
![right3](https://user-images.githubusercontent.com/58376020/125491865-e0d74884-dfa9-4cf7-acc8-32c9a04a7739.png)
#### Your Project
![wrong3](https://user-images.githubusercontent.com/58376020/125491905-b322b222-e671-45f6-af4e-af70d6076ddc.png)

2021-07-13 16:46 UTC, Shaher-11 commented on index.html
> +            </ul>
You need to center the icons as shown below
#### Original design
![right2](https://user-images.githubusercontent.com/58376020/125492158-cd6e4368-d7fb-454c-8007-8a95cbdc7b6a.png)

### Your Project
![wrong2](https://user-images.githubusercontent.com/58376020/125492209-e6b3c2fc-755b-4d3e-8bd4-9abe7d6d4991.png)

2021-07-13 16:46 UTC, Shaher-11 commented on index.html
> +            <section class="box-box4">
Kindly use the image on the left part as shown below
![right](https://user-images.githubusercontent.com/58376020/125492431-c7e7c827-d01f-43ef-8785-0490c334d856.png)

2021-07-13 17:30 UTC, herokudev commented on index.html
> +                    </h1>
Hello thanks for your comments, but I think this is not valid as you can se on my app_screenshot my project does not look like that and I am using the same specifications of font and size for this text.

2021-07-13 17:33 UTC, herokudev commented on index.html
> +            </nav>
Thanks, I already made this adding the background as the design.

2021-07-13 18:13 UTC, herokudev commented on index.html
> +                    </em>
OK, already center.

2021-07-13 18:14 UTC, herokudev commented on index.html
> +            </ul>
OK, already center.

2021-07-13 18:17 UTC, herokudev commented on index.html
> +            <section class="box-box4">
OK, image added.

2021-07-13 20:35 UTC, Shaher-11 approved these changes
#### Hello @herokudev,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle::muscle:


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

2021-07-13 20:46 UTC, herokudev commented
Features approved, it's time to merge !!

2021-07-13 20:46 UTC, merged