Two new sections
herokudev/Figma-design pull request #2
Opened 2021-07-14 18:09 UTC by herokudev

This feature has the "My Recent Works" and "About Me" sections.

2021-07-14 19:38 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi @herokudev, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-14 19:38 UTC, arslanbisharat commented on index.html
> +        </article>
- [ ] This section should be enclosed in section tags. Please replace article with section.

2021-07-14 19:38 UTC, arslanbisharat commented on index.html
> +                <p id="box1-title">Multi-Post Stories</p>
- [ ] The tite of the project should have hx tag.

2021-07-14 19:38 UTC, arslanbisharat commented on index.html
> +                    <p id="box2-title">Profesional Art <br>Printing Data</p>
- [ ] The tite of the project should have hx tag.

2021-07-14 19:38 UTC, arslanbisharat commented on index.html
> +                    <p class="box2-title">Profesional Art <br>Printing Data</p>
- [ ] The tite of the project should have hx tag.

2021-07-14 19:38 UTC, arslanbisharat commented on index.html
> +                    <p class="box2-title">Profesional Art <br>Printing Data</p>
- [ ] The tite of the project should have hx tag.

2021-07-14 19:38 UTC, arslanbisharat commented on index.html
> +                    <p class="box2-style">See Project</p>
- [ ] This should be a button.

2021-07-14 19:38 UTC, arslanbisharat commented on index.html
> +                    <p class="box2-style">See Project</p>
- [ ] This should be a button.

2021-07-14 19:38 UTC, arslanbisharat commented on index.html
> +                <div id="large-button">
- [ ] This should be a button.

2021-07-14 19:38 UTC, arslanbisharat commented on index.html
> +                <p id="about-me-title">About Me</p>
- [ ] This should use hx tag instead of p tag.

2021-07-14 19:38 UTC, arslanbisharat commented on index.html
> +            <img id="about-vector" src="images/Vector-4.png" alt="">
- [ ] The section should have a proper background image (decorations are always background images, not img tags)

2021-07-14 19:38 UTC, arslanbisharat commented on index.html
> +                <img src="images/btn_resume.png" alt="">
- [ ] The button (e.g., "Get my resume") should be a link `a` or `button` tag, and follow the button styling: Active, Hover and Pressed.

2021-07-14 19:38 UTC, arslanbisharat commented on css/style.css
> +#box1-title {
- [ ] Don't use ids as selectors. IDs should be unique on a page. This means that if you attach a style to an ID, you won't be able to reuse it within the same webpage. Classes, however, can appear on several HTML elements on the same page. Being able to reuse styles is one of the advantages of CSS

2021-07-14 19:38 UTC, arslanbisharat commented on css/style.css
> +#box1-content {
- [ ] Don't use ids as selectors.

2021-07-14 19:38 UTC, arslanbisharat commented on css/style.css
> +#about-me-title {
- [ ] Don't use ids as selectors.

2021-07-14 19:38 UTC, arslanbisharat commented on css/style.css
> +#about-me-content {
- [ ] Don't use ids as selectors.

2021-07-14 19:38 UTC, arslanbisharat commented on css/style.css
> +#about-group {
- [ ] Don't use ids as selectors.

2021-07-14 19:38 UTC, arslanbisharat commented on css/style.css
> +#about-vector {
- [ ] Don't use ids as selectors.

2021-07-14 20:32 UTC, herokudev commented on index.html
> +        </article>
OK, tag changed.

2021-07-14 20:34 UTC, herokudev commented on index.html
> +                <p id="box1-title">Multi-Post Stories</p>
OK, done!

2021-07-14 20:37 UTC, herokudev commented on index.html
> +                    <p id="box2-title">Profesional Art <br>Printing Data</p>
OK, done!

2021-07-14 20:39 UTC, herokudev commented on index.html
> +                    <p class="box2-title">Profesional Art <br>Printing Data</p>
OK, done!

2021-07-14 20:42 UTC, herokudev commented on index.html
> +                    <p class="box2-title">Profesional Art <br>Printing Data</p>
OK, done!

2021-07-14 20:43 UTC, herokudev commented on index.html
> +                <p id="about-me-title">About Me</p>
OK, done!

2021-07-14 20:44 UTC, herokudev commented on css/style.css
> +#box1-title {
OK, done!

2021-07-14 20:45 UTC, herokudev commented on css/style.css
> +#box1-content {
OK, done!

2021-07-14 20:47 UTC, herokudev commented on css/style.css
> +#about-me-title {
OK, done!

2021-07-14 20:47 UTC, herokudev commented on css/style.css
> +#about-me-content {
OK, done!

2021-07-14 20:49 UTC, herokudev commented on css/style.css
> +#about-group {
OK, done!

2021-07-14 20:50 UTC, herokudev commented on css/style.css
> +#about-vector {
OK, done!

2021-07-14 21:14 UTC, herokudev commented on index.html
> +            <img id="about-vector" src="images/Vector-4.png" alt="">
OK, done!

2021-07-14 22:07 UTC, herokudev commented on index.html
> +                    <p class="box2-style">See Project</p>
OK, done!

2021-07-14 22:07 UTC, herokudev commented on index.html
> +                    <p class="box2-style">See Project</p>
OK, done!

2021-07-14 22:08 UTC, herokudev commented on index.html
> +                <div id="large-button">
OK, done!

2021-07-14 22:08 UTC, herokudev commented on index.html
> +                <img src="images/btn_resume.png" alt="">
OK, done!

2021-07-14 22:44 UTC, ahmetbozaci requested changes
# STATUS: Changes Required  ♻️ 

## Hello @herokudev ✋🏼  Nice done with working on last review.However there are still some issues you should fix. Please fix them then your project will be approved.

### ♻️ Request changes ♻️
 

_**Check the comment about that  under the review.**_



 
### Cheers and Happy coding! 💻 👏
![cat on laptop](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)




___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

2021-07-14 22:44 UTC, ahmetbozaci commented on css/style.css
> +  cursor: pointer;
- [ ] You didnt fix last TSE review. Button should follow button styling. Active, Hover and Pressed. Of course it wont work in mobile. It will work in desktop version later.

2021-07-15 15:00 UTC, herokudev commented on css/style.css
> +  cursor: pointer;
OK, done!

2021-07-15 15:09 UTC, abruzy approved these changes
```markdown
Hi @herokudev 👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-15 15:34 UTC, herokudev commented
Merge the approved changes for this feature.

2021-07-15 15:35 UTC, merged