Desktop design
herokudev/Figma-design pull request #5
Opened 2021-07-22 21:50 UTC by herokudev

Changes to create responsive web design for mobile and desktop templates

2021-07-22 23:05 UTC, Shaher-11 requested changes
#### Hello @mach512,

### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:smiley::smiley:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] Check the comments below:point_down:

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

2021-07-22 23:05 UTC, Shaher-11 commented on index.html
> +            <section class="about-me-intro">
Fix the styling of the about me section 
#### Original design
![right](https://user-images.githubusercontent.com/58376020/126719432-d4ce24ec-adb6-4112-ad9e-4e193dce1b70.png)

#### Your Project
![wrong](https://user-images.githubusercontent.com/58376020/126719447-34f6bbe0-3d4d-4af5-a32d-229f3b25d961.png)

2021-07-22 23:05 UTC, Shaher-11 commented on index.html
> +            </section>
Align the items of each list with the title and reduce the extra space as shown below
#### Original design
![right](https://user-images.githubusercontent.com/58376020/126719620-62f924ec-78cd-4e32-8d32-7c58f0ceeb5b.png)

#### Your Project
![wrong](https://user-images.githubusercontent.com/58376020/126719637-1b36016c-c607-476b-89fa-a69599d4c731.png)

2021-07-23 06:54 UTC, Georjane requested changes
### Hello, Team <STUDENTS>, ✋🏽 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

In the future, you can also consider:
- Wrapping all your sections in a `main` tag and then giving this main tag margin: auto; or fixed padding on both the left and right sides. That way your entire project will be centralized, have the same alignment and you won't have to repeat yourself by adding padding to each section

Cheers and Happy coding! 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝 

_Code Reviewer
**[Jane](https://witahgeorjane.tech/)**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-23 06:54 UTC, Georjane commented on css/style.css
> +  }
- [ ] Your navbar still has some alignment issues. You could add padding-left to this element so as to improve the User Interface. I think it will equally make your project more pleasing to the user looking at it. For example, adding `padding: 0 120px; `to the `.desktop-nav` element worked on my end.

**Original Project**
![image](https://user-images.githubusercontent.com/60772732/126745260-735ccf04-7d8f-49ac-937b-9f38467b1d94.png)
**Your Project**
![image](https://user-images.githubusercontent.com/60772732/126745284-72a1672c-1a7a-48b6-85ac-d077e7adb8b7.png)

2021-07-23 06:54 UTC, Georjane commented on css/style.css
>  }
- [ ] Adding padding to this section element will help centralise the element. For example adding a padding of `padding: 0 120px;` worked on my end

2021-07-23 16:49 UTC, Shaher-11 approved these changes
#### Hello @herokudev,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle::muscle:

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

2021-07-23 17:34 UTC, merged